# my global config
global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 127.0.0.1:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['127.0.0.1:9090']

#node节点指标
  - job_name: "node_exporter_coll"
    file_sd_configs:
    - refresh_interval: 1m
      files: 
      - "/etc/prometheus/conf.d/node*.yml"

#burrow指标
  - job_name: "burrow_kafka"
    file_sd_configs:
    - refresh_interval: 30s
      files: 
      - "/etc/prometheus/conf.d/burrow_nod*.yml"

#kafka指标
  - job_name: "kafka_exporter"
    file_sd_configs:
    - refresh_interval: 30s
      files: 
      - "/etc/prometheus/conf.d/kafka_nod*.yml"

#http get 指标
  - job_name: "http_get"
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
    - refresh_interval: 1m
      files:
      - "/etc/prometheus/conf.d/http_get*.yml"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  

#http post 指标
  - job_name: "http_post"
    metrics_path: /probe
    params:
      module: [http_post_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
    - refresh_interval: 1m
      files:
      - "/etc/prometheus/conf.d/http_post*.yml"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  

#http 证书 指标
  - job_name: "ssl_cert"
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
    - refresh_interval: 1m
      files:
      - "/etc/prometheus/conf.d/ssl_cert.yml"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  

#tcp 指标
  - job_name: "check_tcp"
    metrics_path: /probe
    params:
      module: [tcp_connect]
    file_sd_configs:
    - refresh_interval: 1m
      files:
      - "/etc/prometheus/conf.d/check_tcp*.yml"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  

#ping 指标
  - job_name: "check_ping"
    metrics_path: /probe
    params:
      module: [ping] 
    file_sd_configs:
    - refresh_interval: 1m
      files:
      - "/etc/prometheus/conf.d/check_ping*.yml"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 127.0.0.1:9115  

#jvm 指标
  - job_name: "tomcat_jvm"
    metrics_path: /actuator/prometheus
    scrape_interval: 30s
    file_sd_configs:
    - refresh_interval: 1m
      files:
      - "/etc/prometheus/conf.d/tomcat_jvm*.yml"

#jvm 指标
  - job_name: "jvm_management"
    metrics_path: /management/prometheus
    scrape_interval: 30s
    file_sd_configs:
    - refresh_interval: 1m
      files:
      - "/etc/prometheus/conf.d/jvm-management.yml"

#pushgateway
  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
    - targets: ["127.0.0.1:9091"]

#mysql monitor
  - job_name: "MySQL"
    metrics_path: /metrics
    file_sd_configs:
    - refresh_interval: 1m
      files:
      - "/etc/prometheus/conf.d/mysql.yml"
#    relabel_configs:
#      - source_labels: [__address__]
#        regex: (.*)
#        target_labels: __address__
#        replacement: $1

#nacos 指标
  - job_name: "nacos"
    metrics_path: /nacos/actuator/prometheus
    scrape_interval: 30s
    file_sd_configs:
    - refresh_interval: 1m
      files:
      - "/etc/prometheus/conf.d/nacos*.yml"

#doris 指标
  - job_name: "doris"
    metrics_path: /metrics
    scrape_interval: 30s
    file_sd_configs:
    - refresh_interval: 1m
      files:
      - "/etc/prometheus/conf.d/doris.yml"
