groups:
    - name: alert_system
      rules:
      - alert: 监控告警-服务异常
        expr: up  == 0
        for: 1m
        labels:
          serverity: warning
        annotations:
          summary: "{{$labels.job}}服务异常"
          description: "{{$labels.job}}服务,{{$labels.instance}}异常,请尽快处理."

      - alert: 监控告警-主机状态
        expr: up == 0
        for: 5m
        labels:
          serverity: critical
        annotations:
          summary: "{{$labels.instance}}:服务器宕机"
          description: "{{$labels.instance}}:服务器延时超过5分钟"

      - alert: 监控告警-CPU使用率
        expr: 100-(avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by(instance)* 100) > 80
        for: 5m
        labels:
          serverity: warning
        annotations:
          summary: "{{$labels.instance}}主机CPU使用率[5m]超过80%"
          description: "{{$labels.instance}}主机CPU使用率超过80%,当前使用率[{{ humanize $value }}%]."

      - alert: 监控告警-内存使用率
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes > 0.95 
        for: 10m
        labels:
          serverity: warning
        annotations:
          summary: "{{$labels.instance}}主机内存使用率超过95%"
          description: "{{$labels.instance}}主机内存使用率超过95%,当前使用率[{{ humanize $value }}%]."

      - alert: 监控告警-磁盘使用率
        expr: 100-(node_filesystem_free_bytes{fstype=~"ext4|xfs", mountpoint=~"/"}/node_filesystem_size_bytes {fstype=~"ext4|xfs", mountpoint=~"/"}*100) > 80
        for: 5m
        labels:
          serverity: warning
        annotations:
          summary: "{{$labels.instance}}主机磁盘使用率超过80%"
          description: "{{$labels.instance}}主机磁盘使用率超过80%,当前使用率[{{ humanize $value }}%]."

      - alert: 监控告警-网络流入
        expr: ((sum(rate (node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])) by (instance)) / 100) > 102400
        for: 1m
        labels:
          serverity: warning
        annotations:
          summary: "{{$labels.instance}}主机{{$labels.mountpoint}} 流入网络带宽过高！"
          description: "{{$labels.instance}}主机{{$labels.mountpoint }}流入网络带宽持续2分钟高于100M. RX带宽使用率{{humanize $value}}"
 
      - alert: 监控告警-网络流出
        expr: ((sum(rate (node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])) by (instance)) / 100) > 102400
        for: 1m
        labels:
          serverity: warning
        annotations:
          summary: "{{$labels.instance}}主机{{$labels.mountpoint}} 流出网络带宽过高！"
          description: "{{$labels.instance}}主机{{$labels.mountpoint }}流出网络带宽持续2分钟高于100M. RX带宽使用率{{humanize $value}}"

    - name: alert_network 
      rules:
        - alert: 监控告警-TCP端口连通性
          expr: probe_success{job="check_tcp"} == 0
          for: 1m
          labels:
            serverity: critical
          annotations:
            summary: "接口/主机/端口 {{$labels.instance}} 无法访问!"
            description: "{{$labels.project}} {{$labels.instance}} 无法访问!"

        - alert: 监控告警-WEB可用性
          expr: probe_success{job="http_get"} == 0
          for: 2m
          labels:
            serverity: critical
          annotations:
            summary: "接口/主机/端口 {{$labels.instance}} 无法访问!"
            description: "{{$labels.project}} {{$labels.instance}} 无法访问!"

        - alert: 监控告警-ICMP线路质量监控
          expr: probe_success{job="check_ping"} == 0
          for: 2m
          labels:
            serverity: critical
          annotations:
            summary: "接口/主机/端口 {{$labels.instance}} 无法访问!"
            description: "{{$labels.project}} {{$labels.instance}} 无法访问!"
